### ISSUE TITLE
想請教一個問題不知方便嗎?

### ISSUE THREAD

**Issue by billchen198318** [Lawrence-Huang/zoobalancer#2]
您好
看了你您再 JConf youtube上介紹 ZooKeeper 影片覺得很棒，想請教一個問題不知方便嗎?
就是如果有一個內部資訊網是由多個 webApps ( war ) 組成，

舉例:
包含
 SYS (核心) ，
FNSYS ( 財務) ，
ARSYS (會計) ， 
HRM (人資)，
COMM (共用&PDF報表 server)，
BANK-CORE (銀行核心)，
CAR (車險)，FIRE (火險)，MAR(海水險)，HPS(人壽)，旅險..... 等等
由數十個的 war 組成一個金融業核心架構，
每個 war 都是獨立專案, 但是都是 extends SYS 基本底層架構( sys會幫別的war產生 http-session )，
統一由 SYS 單一登入Sign in，
這些 war 本身也能佈署再多個不同的 server 上，也能多server佈署一樣重複的 war。
由  SYS 會自動導向。

問題是:
假如使用者再 FNSYS 財務系統中的, 繳款單功能，操作查詢Query，這時進入某張收費單進行修Edit 改作業，
假如突然間 ap-server-A上的 FNSYS 很慢，這時 ZooKeeper 決定把使用者操作的 submit (確認繳款轉收費) 導向至 ap-server-B上的 FNSYS，
那使用者 ap-server-A 畫面上的操作( view page ) 輸入欄位的資料其實並不再 ap-server-B 中 (如頁面上的輸入欄位，ap-server-A 轉到 ap-server-B 要保留 ap-server-A 畫面上一模一樣的東西才可以
為了保持轉換 server能保持畫面一致，我所在的銀行業是用自己寫的軟體Loadbalance，之前公司買過百萬的硬體Loadbalance，效果也達不到能再業務邏輯操作中切換)，
這樣有辦法使用 ZooKeeper來處理掉嗎？
還是變成必須把所有 view page & http-session & page compoment 所用到的東西&資料全部存入保持至  ZooKeeper 中。

還是 ZooKeeper 只是再 user 進入系統前，決定去用那台 ap-server ，那再業務邏輯操作中當中也能決定切換嗎?
因為看了您的 github repo 範例，覺得好像沒法連業務邏輯操作也能瞬間切換。

還有例如一些 session LIB 如 apache-shiro or spring security 也能被  ZooKeeper 同步嗎 ?

問這些問題可能很突兀。

謝謝你

**Comment by Lawrence-Huang** [comment]
你好：

是的，我的範例也沒有辦法做交易的瞬間切換，因為如果要做到交易的瞬間切換就會涉及到XA交易，所以我是讓用戶導向到同一台主機直到session結束。

另外，是否要把用戶的資料存在zookeeper中，我是持反對的意見，因為zookeeper的寫入速度算不上快，只算得上堪用而已。你有考慮過使用memcached嗎？memcached也是應用蠻廣泛的快取系統，不過現在我就不清楚了，好幾年沒碰這的東西。

**Comment by billchen198318** [comment]
謝謝您的回覆

其實一個金融業 "內部資訊網" 核心系統，不使用 memcached 是沒有很大的影響的，
除非是internet透通平台才比較有需要使用 memcached 

您的影片很棒

謝謝
